image: docker:latest
services:
  - docker-dind

stages:
  - build
  - test

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/jeizsm/telegram-bot:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/jeizsm/telegram-bot:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE dogma
    - docker run $CONTAINER_TEST_IMAGE credo
    - docker run $CONTAINER_TEST_IMAGE test
